# Generated by Django 4.0 on 2022-09-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(help_text='Debit or credit', verbose_name='card number')),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard')], max_length=250)),
                ('exp_date', models.DateTimeField(verbose_name='expiration date')),
                ('secu_code', models.IntegerField(verbose_name='Security code')),
                ('billing_address', models.CharField(max_length=1520)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'Credit_Card',
                'verbose_name_plural': 'Credit_Cards',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], max_length=250)),
                ('routing_num', models.IntegerField(help_text='Debit or credit', verbose_name='Routing number')),
                ('account_num', models.IntegerField(help_text='Account number', verbose_name='Account number')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'Bank_Account',
                'verbose_name_plural': 'Bank_Accounts',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
