# Generated by Django 4.0 on 2022-09-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'managed': True, 'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'managed': True, 'verbose_name': 'Credit card', 'verbose_name_plural': 'Credit cards'},
        ),
    ]
